---

- hostname: name={{ siftrem_hostname }}
  when: siftrem_hostname is defined
- name: Add new hostname in /etc/hosts (local resolv)
  replace:
    "dest='/etc/hosts' regexp='^127.0.0.1       localhost' replace='127.0.0.1       localhost {{ siftrem_hostname }}'"
  when: siftrem_hostname is defined

- name: Restrict sshd config
  lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
  with_items:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin without-password' }

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: check ruby spec permissions
  file: "dest=/home/{{ sift_user }}/.gem/specs state=directory mode=0755 owner={{ sift_user }}"

## https://answers.launchpad.net/ubuntu/+source/snort/+question/262496
- name: Ubuntu | snort noninteractive settings - dir
  file: dest=/etc/snort state=directory mode=0755
- name: Ubuntu | snort noninteractive settings - conf
  lineinfile: dest=/etc/snort/snort.debian.conf line="{{ item }}" mode=0755 backup=yes create=yes
  with_items:
    - 'DEBIAN_SNORT_HOME_NET="any"'
    - "DEBIAN_SNORT_INTERFACE=\"{{ __ubuntu_if }}\""

- name: Debian | Extra packages install
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - "{{ siftrem_extra_pkgs }}"
    - "{{ __ubuntu_packages }}"

- include: ramdisk.yml
  when: ramdisk_path is defined and ramdisk_size is defined

- name: Debian | open-vm-tools install
  apt: name={{item}} state=present
  with_items:
    - open-vm-tools
  when: vm

- name: Debian | Remove some packages
  apt: name={{item}} state=absent
  with_items:
    - rpcbind
    - xterm
#    - netcat-traditional
    - cups-client

- name: Review some limits
  lineinfile: dest=/etc/security/limits.d/openfiles regexp="^{{ sift_user }}\t\thard\tnofiles\t\t2048" line="{{ sift_user }}\t\thard\tnofiles\t\t2048" state=present create=yes

## Extra tools
- name: create toolset root dir
  file: dest={{ siftrem_toolsetdir }} mode=0755 owner={{ sift_user }} state=directory

- name: git clone extra tools
  git:
    repo={{ item }}
    dest={{ siftrem_toolsetdir }}/{{ item | basename }}
  with_items: "{{ siftrem_extra_git }}"
  become: yes
  become_user: "{{ sift_user }}"

- name: python build extra tools
  command: "python setup.py install chdir={{ siftrem_toolsetdir }}/{{ item }}"
  with_items: "{{ siftrem_extra_git_python_build }}"
  become: yes

- stat: path=/usr/local/bin/faup
  register: faup
- name: Debian | faup dependencies
  apt: name={{item}} state=present
  with_items:
    - cmake
  when: not faup.stat.exists
- name: faup | compile
  command: "{{ item }} chdir={{ siftrem_toolsetdir }}/faup/build"
  with_items:
    - cmake ..
    - make
  become: yes
  become_user: "{{ sift_user }}"
  when: not faup.stat.exists
- name: ensure appropriate path for shared libraries
  lineinfile: dest=/etc/ld.so.conf.d/x86_64-linux-gnu.conf line='^/usr/local/lib/x86_64-linux-gnu'
- name: faup | install
  command: "{{ item }} chdir={{ siftrem_toolsetdir }}/faup/build"
  with_items:
    - make install
  become: yes
  when: not faup.stat.exists
  notify:
    - run ldconfig
- name: download {{ item.url | basename }}
  get_url: url={{ item.url }}
    dest={{ siftrem_toolsetdir }}/{{ item.url | basename }}
    mode=0400
    owner={{ sift_user }}
    sha256sum={{ item.s }}
  with_items: "{{ siftrem_extra_dl }}"

## https://code.google.com/p/volatility/wiki/SampleMemoryImages
- file: dest={{ siftrem_toolsetdir }}/sample state=directory owner={{ sift_user }}

- stat: path={{ siftrem_toolsetdir }}/sample/xp-infected.tgz
  register: dldone
- name: Download memory samples
  get_url: url={{ item }}
    dest={{ siftrem_toolsetdir }}/sample
    owner={{ sift_user }}
    mode=0600
  with_items:
    - http://www.cfreds.nist.gov/mem/memory-images.rar
#    - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/1/zeus.vmem.zip
    - http://www.mediafire.com/file/yxqodp1p2aca91x/0zapftis.rar
#    - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/11/sality.vmem.zip
    - http://dl.dropbox.com/u/21148428/xp-clean.tgz
    - http://dl.dropbox.com/u/21148428/xp-infected.tgz
  when: not dldone.stat.exists
  ignore_errors: true

- npm: name=casperjs path={{ siftrem_toolsetdir }}/casperjs
  ignore_errors: true

- include: volatility-modules.yml
  become: yes
  become_user: "{{ sift_user }}"
#- include: rekall.yml
- include: yara-signature.yml
  become: yes
  become_user: "{{ sift_user }}"
- include: iocrepository.yml
  become: yes
  become_user: "{{ sift_user }}"

- include: powershell.yml
- include: maltego.yml


