---

- name: Rekall | dependencies install
  apt: name={{item}} state=present
  with_items:
#    - python3
    - python-virtualenv

- name: Install recent setuptools inside virtualenv
  pip: "name=setuptools version=8.0 state=present virtualenv=/home/{{ sift_user }}/env-rekall"

- name: Install rekal inside virtualenv
  pip: "name={{item}} state=present virtualenv=/home/{{ sift_user }}/env-rekall"
  with_items:
    - wheel
    - rekall

